server:
  port: 8888

spring:
  application:
    name: flowersea-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangqiusky/flowersea/config-respository

